### PR TITLE
PGP: Reassign things owned by user before dropping that user

### LINKED ISSUE #5: Issues unbinding services
Hi!

Attempting to unbind a service binding that has created tables would fail, with an error message of something like

> Service instance rails-example-db: Service broker error: pq: role \"sb_de4c5385-e66e-4529-ac7c-2b1f80ebaa9b\" cannot be dropped because some objects depend on it

This is because that user is the owner of the newly created tables.  `REASSIGN OWNED BY sb_de4c5385-e66e-4529-ac7c-2b1f80ebaa9b TO <other user>` helps.  Note that that statement only affects tables in the current database (so a reconnect to the relevant database is required to actually fix things).

I'll probably write up a PR in a few days if nobody else gets to it first :stuck_out_tongue:

### PR DESCRIPTION
**Pull request by mook-as**
Postgres will refuse to drop users who still own tables.  We will need to reassign ownership before dropping it.  However, the Postgres `REASSIGN OWNED BY` statement only affects things in the current database; in order for that to work correctly, we will need to reconnect to postgres with the correct database in the parameters.

Fixes #5

### CODE REVIEW

**Comment by Infra-Red** [comment]
Hi @mook-as ! Thanks for submitting PR!
I just verified your PR against RDS Postgres instance and I'm getting the following error for `unbind` action:
```
2018-05-16T21:45:28.32+0300 [APP/PROC/WEB/0] ERR {"timestamp":"1526496328.327524424","source":"postgresql-broker","message":"postgresql-broker.unbind.unknown-error","log_level":2,"data":{"binding-id":"393a0cff-3199-4932-b35e-ac4605530205","error":"pq: permission denied to reassign objects","instance-id":"bcabe3c3-f4ee-439e-9e87-a0c8bc84e85d","session":"6"}}
```

But I don't exclude that this error may be AWS RDS specific. WDYT?

**Comment by mook-as** [comment]
Hi @Infra-Red! Thanks for the quick response!

I have been testing against a helm-deployed local postgres ([mook-as:cf-postgresql-broker/helmified](https://github.com/mook-as/cf-postgresql-broker/tree/helmified) — needs more docs on how to set things up, but the commands involved are at the top of [values.yaml](https://github.com/mook-as/cf-postgresql-broker/blob/helmified/helm/values.yaml)).  It's possible that RDS has different permissions because it's (probably) a shared database.  Not sure what the best way to resolve this is; outright deleting the tables seems kind of bad (since one could, theoretically, rebind the service to a different app).

Hmm, I'm not switching the user (just the database) when re-opening the connection; I wonder if switching that to the to-be-dropped user would help. I don't think we have easy access to the correct password at that point though.

**Comment by Infra-Red** [comment]
@mook-as I will verify unbind action against [postgres-boshrelease](https://github.com/cloudfoundry/postgres-release) and merge if it will work as expected. I'm almost 100% sure that this problem is only AWS specific.

**Comment by Infra-Red** [comment]
`cf unbind-service` works as expected when using [postgres-boshrelease](https://github.com/cloudfoundry/postgres-release).

**Comment by Infra-Red** [comment]
@mook-as Thanks for contribution!

**Pull request merged**
